version: "3"

services:
  nuxt:
    image: python:3.7-alpine
    restart: always
    command: sh -c "pip install -r requirements.txt && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      VIRTUAL_HOST: deed-recomentaions.atnartur.ru
      DB_PATH: /srv/db/db.sqlite3
    ports:
      - 8000
    networks:
      - web
    volumes:
      - /home/serveruser/deed-simulation:/srv/db

networks:
  web:
    external:
      name: web
