version: "3"

services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      VIRTUAL_HOST: deed-recomentaions.atnartur.ru
      DB_PATH: /srv/db/db.sqlite3
    ports:
      - 8000
    networks:
      - web
    volumes:
      - /home/serveruser/deed-simulation:/srv/db

networks:
  web:
    external:
      name: web
