# Generated by Django 2.1.2 on 2019-03-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='users',
        ),
        migrations.AlterField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(related_name='users', through='main.Choice', to='main.Course'),
        ),
    ]
